### ISSUE TITLE
Alternative button name linking

### ISSUE THREAD

**Issue by KairuByte** [kala13x/flipper-xremote#6]
I often name my buttons on the fly, directly on the flipper. This means I short form some names. Things like `Vol_up` or `Chan+`. It might be a good idea to look for those button names as well, since I know many existing .ir files out there use different file names.

Suggestions:
- Look for both `[space]` and `_` as a separator, but also include no separator. 
- Look for both `Up` and `+` for volume control. (And equivalent for the reverse.)
- Look for `Next`, `Up`, and `+` for channel control. (and equivalent for the reverse.)
- Look for short forms such as `Vol`, `Vlm`, `Chan`, and `Ch` on top of the long form. Maybe even `C` and `V`.

**Comment by kala13x** [comment]
@KairuByte Hi, thanks for opening the issue.

Actually that's a good idea.
But I'm going to make this feature configurable.

It will be possible to enable/disable additional button name linking in order to not affect performance because when the button is pressed it will start to search all possible variants until it finds one and that may have some delay. 

Some mapping file can be also implemented for additional names. 
For example:

```
Chan_up: Up, Chup, ch+, Chan+
Vol_up: vol+, v+, +
...
```

This way we can teach the flipper what alternative names to look for the button

**Comment by kala13x** [comment]
@KairuByte Hi, sorry for the late reply. I was very busy with work. 

I've finished the alternate names feature, and the code has already been merged into the main branch. I've also made a [pull request](https://github.com/flipperdevices/flipper-application-catalog/pull/311) to the app catalog, and hopefully, the new version will appear in the catalog soon.

I will close this issue. If you consider it necessary, feel free to reopen it.

P.S. That was an awesome idea. Thank you.
